name:  OpenDevOps-Wekan
description: |
   Kanban Practice of Wekan Image for Open DevOps Pipeline 
version:  1.0.0
category:  CA
maintainer:  open.devops
license:  Apache 2
projectURL: https://github.com/ open-devops/docker-ca-wekan
